sudo: required # super user permission
services:
  - docker # travis, we need a copy of docker running

before_install:
  - docker build -t nfabacus/docker-frontend -f Dockerfile.dev . # use current directory to build docker image.

script:
  - docker run nfabacus/docker-frontend npm run test -- --coverage
